name: Release
on:
  push:
    branches:
      - main
      - rc

permissions:
  contents: write

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check
        run: pnpm test & pnpm lint

      - name: Build
        run: pnpm build

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm release
